### ISSUE TITLE
Deployment error in migrations or setup script

### ISSUE THREAD

**Issue by dorthrithil** [LocalCrag/LocalCragApp#421]
[2024-07-28 08:31:40] Added uuid-ossp extension to database.
[2024-07-28 08:31:40] Added fuzzystrmatch extension to database.
[2024-07-28 08:31:44] Traceback (most recent call last):
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
[2024-07-28 08:31:44]     self.dialect.do_execute(
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
[2024-07-28 08:31:44]     cursor.execute(statement, parameters)
[2024-07-28 08:31:44] psycopg2.errors.NotNullViolation: null value in column "slug" of relation "users" violates not-null constraint
[2024-07-28 08:31:44] DETAIL:  Failing row contains (c2d4dd12-45aa-4aa2-b61f-c199b32d8140, 2024-07-28 08:31:44.487649, null, $pbkdf2-sha256$29000$tjZGKAXgfG9NCWGMsVYKYQ$9GL7vgk9KJmpIp6D.zvM..., , , , f, null, null, null, de, null, null, f, f, null, null, null, f, null, f).
[2024-07-28 08:31:44] 
[2024-07-28 08:31:44] 
[2024-07-28 08:31:44] The above exception was the direct cause of the following exception:
[2024-07-28 08:31:44] 
[2024-07-28 08:31:44] Traceback (most recent call last):
[2024-07-28 08:31:44]   File "/workspace/server/src/util/scripts/database_setup.py", line 22, in <module>
[2024-07-28 08:31:44]     setup_database()
[2024-07-28 08:31:44]   File "/workspace/server/src/util/scripts/database_setup.py", line 18, in setup_database
[2024-07-28 08:31:44]     script()
[2024-07-28 08:31:44]   File "/workspace/server/src/util/scripts/add_superadmin.py", line 20, in add_superadmin
[2024-07-28 08:31:44]     user = create_user(user_data)
[2024-07-28 08:31:44]            ^^^^^^^^^^^^^^^^^^^^^^
[2024-07-28 08:31:44]   File "/workspace/server/src/helpers/user_helpers.py", line 26, in create_user
[2024-07-28 08:31:44]     db.session.commit()
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
[2024-07-28 08:31:44]     return self._proxied.commit()
[2024-07-28 08:31:44]            ^^^^^^^^^^^^^^^^^^^^^^
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2017, in commit
[2024-07-28 08:31:44]     trans.commit(_to_root=True)
[2024-07-28 08:31:44]   File "<string>", line 2, in commit
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
[2024-07-28 08:31:44]     ret_value = fn(self, *arg, **kw)
[2024-07-28 08:31:44]                 ^^^^^^^^^^^^^^^^^^^^
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1302, in commit
[2024-07-28 08:31:44]     self._prepare_impl()
[2024-07-28 08:31:44]   File "<string>", line 2, in _prepare_impl
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
[2024-07-28 08:31:44]     ret_value = fn(self, *arg, **kw)
[2024-07-28 08:31:44]                 ^^^^^^^^^^^^^^^^^^^^
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1277, in _prepare_impl
[2024-07-28 08:31:44]     self.session.flush()
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4341, in flush
[2024-07-28 08:31:44]     self._flush(objects)
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4476, in _flush
[2024-07-28 08:31:44]     with util.safe_reraise():
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
[2024-07-28 08:31:44]     raise exc_value.with_traceback(exc_tb)
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4437, in _flush
[2024-07-28 08:31:44]     flush_context.execute()
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
[2024-07-28 08:31:44]     rec.execute(self)
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
[2024-07-28 08:31:44]     util.preloaded.orm_persistence.save_obj(
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
[2024-07-28 08:31:44]     _emit_insert_statements(
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
[2024-07-28 08:31:44]     result = connection.execute(
[2024-07-28 08:31:44]              ^^^^^^^^^^^^^^^^^^^
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
[2024-07-28 08:31:44]     return meth(
[2024-07-28 08:31:44]            ^^^^^
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
[2024-07-28 08:31:44]     return connection._execute_clauseelement(
[2024-07-28 08:31:44]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
[2024-07-28 08:31:44]     ret = self._execute_context(
[2024-07-28 08:31:44]           ^^^^^^^^^^^^^^^^^^^^^^
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
[2024-07-28 08:31:44]     return self._exec_single_context(
[2024-07-28 08:31:44]            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
[2024-07-28 08:31:44]     self._handle_dbapi_exception(
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
[2024-07-28 08:31:44]     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
[2024-07-28 08:31:44]     self.dialect.do_execute(
[2024-07-28 08:31:44]   File "/workspace/server/.local/share/virtualenvs/server-f-U7U_HN/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
[2024-07-28 08:31:44]     cursor.execute(statement, parameters)
[2024-07-28 08:31:44] sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "slug" of relation "users" violates not-null constraint
[2024-07-28 08:31:44] DETAIL:  Failing row contains (c2d4dd12-45aa-4aa2-b61f-c199b32d8140, 2024-07-28 08:31:44.487649, null, $pbkdf2-sha256$29000$tjZGKAXgfG9NCWGMsVYKYQ$9GL7vgk9KJmpIp6D.zvM..., , , , f, null, null, null, de, null, null, f, f, null, null, null, f, null, f).
[2024-07-28 08:31:44] 
[2024-07-28 08:31:44] [SQL: INSERT INTO users (password, email, new_email, new_email_hash, new_email_hash_created, firstname, lastname, activated, activated_at, reset_password_hash, reset_password_hash_created, language, avatar_id, superadmin, admin, moderator, member, slug, id, time_created, time_updated, created_by_id) VALUES (%(password)s, %(email)s, %(new_email)s, %(new_email_hash)s, %(new_email_hash_created)s, %(firstname)s, %(lastname)s, %(activated)s, %(activated_at)s, %(reset_password_hash)s, %(reset_password_hash_created)s, %(language)s, %(avatar_id)s::UUID, %(superadmin)s, %(admin)s, %(moderator)s, %(member)s, %(slug)s, %(id)s::UUID, %(time_created)s, %(time_updated)s, %(created_by_id)s::UUID)]
[2024-07-28 08:31:44] [parameters: {'password': '$pbkdf2-sha256$29000$tjZGKAXgfG9NCWGMsVYKYQ$9GL7vgk9KJmpIp6D.zvM4.6vGQoUhhK14So/uRh0Mcw', 'email': '', 'new_email': None, 'new_email_hash': None, 'new_email_hash_created': None, 'firstname': '', 'lastname': '', 'activated': False, 'activated_at': None, 'reset_password_hash': None, 'reset_password_hash_created': None, 'language': 'de', 'avatar_id': None, 'superadmin': False, 'admin': False, 'moderator': False, 'member': False, 'slug': None, 'id': UUID('c2d4dd12-45aa-4aa2-b61f-c199b32d8140'), 'time_created': datetime.datetime(2024, 7, 28, 8, 31, 44, 487649), 'time_updated': None, 'created_by_id': None}]
[2024-07-28 08:31:44] (Background on this error at: https://sqlalche.me/e/20/gkpj)

**Comment by dorthrithil** [comment]
Cannot reproduce this anymore. Changes of @BlobbyBob have presumably fixed it
