### ISSUE TITLE
Add superadmin script throws error in DO deployments

### ISSUE THREAD

**Issue by dorthrithil** [LocalCrag/LocalCragApp#538]
[2024-12-16 22:00:28] The above exception was the direct cause of the following exception:
[2024-12-16 22:00:28] 
[2024-12-16 22:00:28] Traceback (most recent call last):
[2024-12-16 22:00:28]   File "/workspace/server/src/util/scripts/database_setup.py", line 22, in <module>
[2024-12-16 22:00:28]     setup_database()
[2024-12-16 22:00:28]   File "/workspace/server/src/util/scripts/database_setup.py", line 18, in setup_database
[2024-12-16 22:00:28]     script()
[2024-12-16 22:00:28]   File "/workspace/server/src/util/scripts/add_superadmin.py", line 20, in add_superadmin
[2024-12-16 22:00:28]     user = create_user(user_data)
[2024-12-16 22:00:28]            ^^^^^^^^^^^^^^^^^^^^^^
[2024-12-16 22:00:28]   File "/workspace/server/src/helpers/user_helpers.py", line 26, in create_user
[2024-12-16 22:00:28]     db.session.commit()
...
[2024-12-16 22:00:28] sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "slug" of relation "users" violates not-null constraint
[2024-12-16 22:00:28] DETAIL:  Failing row contains (a62ce..., ....
[2024-12-16 22:00:28]

**Comment by dorthrithil** [comment]
There were missing env vars for the superadmin. Probably it's fixed now, have to watch this when deploying next time

**Comment by dorthrithil** [comment]
works now
